config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "menu_juices/index"
  get "menu_juices/show"
  get "menu_juices/new"
  get "menu_juices/create"
  get "menu_juices/edit"
  get "menu_juices/update"
  get "menu_juices/destroy"
  get "menu_juices/index"
  get "menu_juices/show"
  get "menu_juices/create"
  get "menu_juices/update"
  resources :orders
  resources :menu_mains
  root "welcome#welcome"
  resources :restaurants
  resources :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu_main.rb
# frozen_string_literal: true

class MenuMain < ApplicationRecord
end

app/controllers/menu_mains_controller.rb
# frozen_string_literal: true

# controller to menu
class MenuMainsController < ApplicationController
  before_action :set_menu_main, only: %i[show edit update destroy]

  # GET /menu_mains or /menu_mains.json
  def index
    @menu_mains = MenuMain.all
  end

  # GET /menu_mains/1 or /menu_mains/1.json
  def show; end

  # GET /menu_mains/new
  def new
    @menu_main = MenuMain.new
  end

  # GET /menu_mains/1/edit
  def edit; end

  # POST /menu_mains or /menu_mains.json
  def create
    @menu_main = MenuMain.new(menu_main_params)

    respond_to do |format|
      if @menu_main.save
        format.html { redirect_to @menu_main, notice: "Menu main was successfully created." }
        format.json { render :show, status: :created, location: @menu_main }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_mains/1 or /menu_mains/1.json
  def update
    respond_to do |format|
      if @menu_main.update(menu_main_params)
        format.html { redirect_to @menu_main, notice: "Menu main was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_main }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_mains/1 or /menu_mains/1.json
  def destroy
    @menu_main.destroy
    respond_to do |format|
      format.html { redirect_to menu_mains_url, notice: "Menu main was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_main
    @menu_main = MenuMain.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def menu_main_params
    params.require(:menu_main).permit(:name, :description, :price)
  end
end

app/helpers/menu_mains_helper.rb
# frozen_string_literal: true

# module to menu main
module MenuMainsHelper
end

app/views/menu_mains/_form.html.erb
<%= form_with(model: menu_main, local: true) do |form| %>
  <% if menu_main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_main.errors.count, "error") %> prohibited this menu_main from being saved:</h2>

      <ul>
        <% menu_main.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_mains/edit.html.erb
<h1>Editing Menu Main</h1>

<%= render 'form', menu_main: @menu_main %>

<%= link_to 'Show', @menu_main %> |
<%= link_to 'Back', menu_mains_path %>

app/views/menu_mains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Mains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_mains.each do |menu_main| %>
      <tr>
        <td><%= menu_main.name %></td>
        <td><%= menu_main.description %></td>
        <td><%= menu_main.price %></td>
        <td><%= link_to 'Show', menu_main %></td>
        <td><%= link_to 'Edit', edit_menu_main_path(menu_main) %></td>
        <td><%= link_to 'Destroy', menu_main, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Main', new_menu_main_path %>

app/views/menu_mains/new.html.erb
<h1>New Menu Main</h1>

<%= render 'form', menu_main: @menu_main %>

<%= link_to 'Back', menu_mains_path %>

app/views/menu_mains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_main.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu_main.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_main.price %>
</p>

<%= link_to 'Edit', edit_menu_main_path(@menu_main) %> |
<%= link_to 'Back', menu_mains_path %>